### PR TITLE
refactor: settings sub-pages

### PR DESCRIPTION
**Pull request by tristanhcole**
**Describe the Pull Request**
Refactor settings sub-pages to use ant design.

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [x] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver
- [ ] Add release notes to [unreleased changelog](https://github.com/teamsempo/SempoBlockchain/blob/master/CHANGELOG.md#unreleased)

### CODE REVIEW

**Comment by tristanhcole** [comment]
[Refactor settings sub pages](https://trello.com/c/eWzzIIWU/846-refactor-settings-sub-pages)

**Review by michielderoos — CHANGES_REQUESTED** [review]
Looks good! One little issue-- after resetting passwords, the reset password page continually says "Password Successfuly Changed". 
image

**Comment by tristanhcole** [comment]
> Looks good! One little issue-- after resetting passwords, the reset password page continually says "Password Successfuly Changed".
> image

Good find. I think that’s our of scope of this PR but worth fixing in another one!

**Comment by tristanhcole** [comment]
Closed by #718

**Pull request closed without merging**
