### PR TITLE
feat: header with breadcrumbs

### PR DESCRIPTION
**Pull request by tristanhcole**
**Describe the Pull Request**
Adds a header component with a back button and breadcrumbs. Automatically builds based on paths. Also has the capacity for custom routes to be passed from the nav.jsx component.

I'm unsure if we should just have breadcrumbs, or a title and back button also. See images below.
Screen Shot 2021-04-23 at 4 22 23 pm

Screen Shot 2021-04-23 at 4 21 59 pm

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [x] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver
- ~~[ ] Add release notes to [unreleased changelog](https://github.com/teamsempo/SempoBlockchain/blob/master/CHANGELOG.md#unreleased)~~

### CODE REVIEW

**Comment by tristanhcole** [comment]
[[Medium] (8 hrs) Several screens would benefit from a “cancel/exit/back” button - Breadcrumbs](https://trello.com/c/YZwibMFf/779-medium-8-hrs-several-screens-would-benefit-from-a-cancel-exit-back-button-breadcrumbs)

**Review by michielderoos — CHANGES_REQUESTED** [review]
Mostly looks pretty good! Pretty slick library! Just a few notes and suggestions:  
image
When clicking the "users" breadcrumb from a user page, it takes you to `/users` (which 404s). Should the parent of a user also be a transfer account? (I.e. `Home/Accounts/Single Transfer Account 4701/Single User 4738 `?  
  
Not a technical note, but I'm also not really sure I like the naming scheme-- a title like `Single User 4738` seems awkward as a large header when you could use either `User` or `John Smith` IMO.

**Comment by tristanhcole** [comment]
> Mostly looks pretty good! Pretty slick! Just a few notes and suggestions:
> image
> When clicking the "users" breadcrumb from a user page, it takes you to `/users` (which 404s). Should the parent of a user also be a transfer account? (I.e. `Home/Accounts/Single Transfer Account 4701/Single User 4738 `?

Agree with this in practice, but I think the breadcrumbs should follow URL nav as much as possible. This is hard to implement and out of scope of current implementation IMO. 

> Not a technical note, but I'm also not really sure I like the naming scheme-- a title like `Single User 4738` seems awkward as a large header when you could use either `User` or `John Smith` IMO.

I've changed to just the Singular noun, i.e. `User`. Hard to implement the specific user name as `Page.tsx` is a parent component of the page where the details are loaded into Redux.

**Comment by tristanhcole** [comment]
> > Mostly looks pretty good! Pretty slick! Just a few notes and suggestions:
> > image
> > When clicking the "users" breadcrumb from a user page, it takes you to `/users` (which 404s). Should the parent of a user also be a transfer account? (I.e. `Home/Accounts/Single Transfer Account 4701/Single User 4738 `?
> 
> Agree with this in practice, but I think the breadcrumbs should follow URL nav as much as possible. This is hard to implement and out of scope of current implementation IMO. In the meantime, I've changed it so it doesn't go to an error 404 page at least.

As I think on this more, I think you are right on this. I'm just not sure if it should be in scope of the ticket or not 🤔

**Comment by michielderoos** [comment]
> As I think on this more, I think you are right on this. I'm just not sure if it should be in scope of the ticket or not

@tristanhcole I think it would be, just because `Users` just takes you to the metrics page which I think is a bit confusing.

**Review by michielderoos — COMMENTED** [review]
Just a couple things-- not sure `Users` should go to the metrics page (per the other comment), and I think it would make sense to rename `Bulk` to `Bulk Disbursements` here:
image  
Looks good otherwise!

**Review by michielderoos — APPROVED** [review]
Looks great!

**Pull request merged**
