### PR TITLE
Saved filters

### PR DESCRIPTION
**Pull request by michielderoos**
**Describe the Pull Request**

Saved filters! Note: The naming of some things is a bit clunky, but we'll be able to remove the old filters api and tidy it all up once the new FE is done  

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [x] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver

### CODE REVIEW

**Comment by michielderoos** [comment]
[Saved Filters Component](https://trello.com/c/GCVlXyuD/714-saved-filters-component)

**Review by enjeyw — CHANGES_REQUESTED** [review]
Existing code is good but can we also add a delete method since last time we had saved filter we quickly ended up with tonnes of junk ones lol

**Comment by michielderoos** [comment]
> Existing code is good but can we also add a delete method since last time we had saved filter we quickly ended up with tonnes of junk ones lol

Done!

**Comment by tristanhcole** [comment]
No longer needed

**Pull request closed without merging**
