### PR TITLE
feat: pdf export for metrics

### PR DESCRIPTION
**Pull request by tristanhcole**
**Describe the Pull Request**
~~Adding PDF export to metric cards. To be honest, I'm not _super happy_ with the outcome on this (low pdf quality and could be formatted better), but unsure if it makes sense to rebuild with a more complex package such as [react-pdf](https://github.com/diegomura/react-pdf). I thought it would make sense to put up a PR and get some feedback. So far relatively little time on this ticket ~ 2.5 hours
[Transfers_all_payments_volume (5).pdf](https://github.com/teamsempo/SempoBlockchain/files/6154380/Transfers_all_payments_volume.5.pdf)
Screen Shot 2021-03-17 at 3 17 13 pm~~

Refactor to use `@react-pdf/renderer` and `html2canvas`. A much higher quality PDF and better maintained package.

[Transfers_all_payments_volume (12).pdf](https://github.com/teamsempo/SempoBlockchain/files/6294010/Transfers_all_payments_volume.12.pdf)

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [ ] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [ ] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver
- [ ] Add release notes to [unreleased changelog](https://github.com/teamsempo/SempoBlockchain/blob/master/CHANGELOG.md#unreleased)

### CODE REVIEW

**Comment by tristanhcole** [comment]
[[High] (8 hrs) Export metrics as PDF](https://trello.com/c/BoGwYLOg/773-high-8-hrs-export-metrics-as-pdf)

**Review by michielderoos — COMMENTED** [review]
The code looks fine! I'm not sure I like the PDF myself either though-- having links and dropdowns is a bit undesirable IMO, and there's also a lot of excess space around the screenshot.

**Review by michielderoos — CHANGES_REQUESTED** [review]
I may be doing something wrong, but the metrics page seems to just load indefinitely for me when I open it

**Review by michielderoos — COMMENTED** [review]
Not sure why this didn't work for me before, cleaned up my env and it works now!  

I think this might be a bug with the library, but I found that if you shrink your window to be narrow (such that dates on the Y axis overlap), and export a PDF, the page will crash. Is there a way to make the screenshot a determined width? That way this bug can't happen, and your screenshot won't change depending on the window size.

**Comment by tristanhcole** [comment]
No longer needed

**Pull request closed without merging**
