### PR TITLE
Add Changelog

### PR DESCRIPTION
**Pull request by tristanhcole**
**Describe the Pull Request**
Add Changelog to the repo as recommended by SOC2 standards. We can release 1.7.70 under https://github.com/teamsempo/SempoBlockchain/releases. Given we version both frontend and backend, adding `server-` and `frontend-` to the prefix of the release version.

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [x] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver

### CODE REVIEW

**Comment by tristanhcole** [comment]
[Add changelog.md](https://trello.com/c/fxKw2sVD/766-add-changelogmd)

**Comment by tristanhcole** [comment]
Closes #207

**Comment by tristanhcole** [comment]
[Add changelog.md](https://trello.com/c/fxKw2sVD/766-add-changelogmd)

**Review by michielderoos — APPROVED** [review]
Just realized I forgot to 👍 !

**Pull request merged**
