### PR TITLE
refactor: organisation lat/lng

### PR DESCRIPTION
**Pull request by tristanhcole**
**Describe the Pull Request**
Add lat/lng to project settings. Change organisation response message.

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [x] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver

### CODE REVIEW

**Comment by tristanhcole** [comment]
[Set default location on map](https://trello.com/c/MNAPOyjc/765-set-default-location-on-map)

**Comment by tristanhcole** [comment]
[When you create a new project, the confirmation message says “new organization created](https://trello.com/c/pmxAIuFb/763-when-you-create-a-new-project-the-confirmation-message-says-new-organization-created)

**Review by michielderoos — CHANGES_REQUESTED** [review]
Would another kind of field be more appropriate? I just can't see the up/down arrows being used for coordinates.   
image

**Comment by tristanhcole** [comment]
> Would another kind of field be more appropriate? I just can't see the up/down arrows being used for coordinates.
> image

Hmmm I did think about this. It's pretty usable to just type in a number (i.e `2.5`) Latitude and Longitude are numbers so made the most sense to keep as number only inputs. 

Any thoughts on alternatives from https://ant.design/components/input/ ?

**Review by michielderoos — APPROVED** [review]
@tristanhcole Fair enough!

**Pull request merged**
