### PR TITLE
Invalidate auth tokens based on IAT

### PR DESCRIPTION
**Pull request by michielderoos**
**Describe the Pull Request**

Invalidate auth tokens based on IAT, this makes it so old tokens are also invalidated by logging out.    
Also makes them expire earlier by default

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [x] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver
- [ ] Add release notes to [unreleased changelog](https://github.com/teamsempo/SempoBlockchain/blob/master/CHANGELOG.md#unreleased)

### CODE REVIEW

**Comment by michielderoos** [comment]
[Session/Authentication Token Not Invalidated After Logout](https://trello.com/c/j7TOg9Nx/983-session-authentication-token-not-invalidated-after-logout)

**Comment by michielderoos** [comment]
[Authentication Token Not validated for Each User.](https://trello.com/c/1i5s7Kfk/968-authentication-token-not-validated-for-each-user)

**Comment by michielderoos** [comment]
[Session Timeout Too Long](https://trello.com/c/tTO7sgMo/989-session-timeout-too-long)

**Comment by michielderoos** [comment]
[Session Timeout Too Long](https://trello.com/c/5NAKz3uP/975-session-timeout-too-long)

**Review by tristanhcole — APPROVED** [review]
Tested. Changes discussed and implemented makes sense to me. Let's try 2-hour default and update on production if we run into frequent user issues.

**Pull request merged**
