### PR TITLE
Naming issues

### PR DESCRIPTION
**Pull request by tristanhcole**
**Describe the Pull Request**
Fixes a few small naming issues on live feed:

- "Reclamation" being classified as a "withdrawal"
- Adds the admin user email for disbursements and reclamations
- Changes `sent` to `paid`

Screen Shot 2020-09-14 at 4 50 40 pm

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes etc.
- [x] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver

### CODE REVIEW

**Comment by tristanhcole** [comment]
[Live Feed action incorrectly labeled](https://trello.com/c/CQPsJ31B/536-live-feed-action-incorrectly-labeled)

**Comment by tristanhcole** [comment]
[Consistent Labeling of Transfer Types across platform](https://trello.com/c/VHsuCaQ1/517-consistent-labeling-of-transfer-types-across-platform)

**Comment by tristanhcole** [comment]
[Naming Issues](https://trello.com/c/xNLpJM2F/472-naming-issues)

**Review by michielderoos — APPROVED** [review]
Tested, works for me 👍

**Pull request merged**
