### PR TITLE
Add support for Commcare

### PR DESCRIPTION
**Pull request by michielderoos**
**Describe the Pull Request**

Commcare is actually extremely similar to Kobo Toolbox as far as we're concerned for this application. Small tweak to attribute preprocessor and we're in business!  

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes etc.
- [x] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver

### CODE REVIEW

**Review by tristanhcole — COMMENTED** [review]
I got a server 500 error when i tried to run this on Commcare's web app for this form https://www.commcarehq.org/a/sempo/apps/view/433391694f09b9295854761d989317dd/

```
<?xml version='1.0' ?>
<data uiVersion="1" version="12" name="Survey"
    xmlns:jrm="http://dev.commcarehq.org/jr/xforms"
    xmlns="http://openrosa.org/formdesigner/4A8E1664-B941-4FC2-BB89-D55F09C6C60D">
    <first_name>tristan</first_name>
    <favorite_chocolate_bar>test</favorite_chocolate_bar>
    <last_name>cole</last_name>
    <phone>0401391418</phone>
    <location>melbourne</location>
    <gender>male</gender>
    <n0:meta
        xmlns:n0="http://openrosa.org/jr/xforms">
        <n0:deviceID>Formplayer</n0:deviceID>
        <n0:timeStart>2020-12-07T16:30:03.898+11</n0:timeStart>
        <n0:timeEnd>2020-12-07T16:30:23.344+11</n0:timeEnd>
        <n0:username>testsempo</n0:username>
        <n0:userID>bc4d5cb0a27548c290ebb1ed804fa78c</n0:userID>
        <n0:instanceID>355fd1e7-bd7d-4d4f-89e7-19319aca69f6</n0:instanceID>
        <n1:appVersion
            xmlns:n1="http://commcarehq.org/xforms">Formplayer Version: 2.47
        </n1:appVersion>
        <n0:drift>0</n0:drift>
    </n0:meta>
</data>
```
trace:
```
Traceback (most recent call last):
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/sentry_sdk/integrations/flask.py", line 90, in sentry_patched_wsgi_app
    environ, start_response
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/sentry_sdk/integrations/wsgi.py", line 129, in __call__
    reraise(*_capture_exception(hub))
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 55, in reraise
    raise value
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/sentry_sdk/integrations/wsgi.py", line 125, in __call__
    _sentry_start_response, start_response, transaction
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/sentry_sdk/integrations/flask.py", line 89, in <lambda>
    return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/Users/tristancole/PycharmProjects/SempoBlockchain/app/server/utils/auth.py", line 151, in wrapper
    return f(*args, **kwargs)
  File "/Users/tristancole/PycharmProjects/SempoBlockchain/app/server/api/user_api.py", line 151, in post
    data = standard_user_preprocess(raw_data, CREATE_USER_SETTINGS)
  File "/Users/tristancole/PycharmProjects/SempoBlockchain/app/server/utils/attribute_preprocessor.py", line 25, in standard_user_preprocess
    insert_settings_from_database(SETTINGS),
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env6/lib/python3.7/site-packages/toolz/functoolz.py", line 634, in pipe
    data = func(data)
  File "/Users/tristancole/PycharmProjects/SempoBlockchain/app/server/utils/attribute_preprocessor.py", line 38, in unwrap_data
    if 'form' in attribute_dict:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by tristanhcole** [comment]
Same error when i install app on android

**Review by tristanhcole — CHANGES_REQUESTED** [review]
See https://github.com/teamsempo/SempoBlockchain/pull/569#pullrequestreview-545842305

**Comment by michielderoos** [comment]
image
  
Found the issue! In the commcare settings, you have to change "Payload Format" to JSON instead of XML.

**Comment by tristanhcole** [comment]
> image
> 
> Found the issue! In the commcare settings, you have to change "Payload Format" to JSON instead of XML.

That will do it!

**Review by tristanhcole — APPROVED** [review]
Tested and LGTM!

Let's ensure we've updated http://docs.withsempo.com/ on how to integrate Commcare (as if I made an error, I'm sure one of our customers will also!).

Maybe this ticket is done https://trello.com/c/uMdQl8qf/710-url-builder?

**Pull request merged**
