### PR TITLE
Add indexes to eth_worker database

### PR DESCRIPTION
**Pull request by michielderoos**
**Describe the Pull Request**

eth_worker DB was missing some indexes. This adds them!  

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes etc.
- [x] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver

### CODE REVIEW

**Comment by michielderoos** [comment]
[Add indexes to eth_worker DB](https://trello.com/c/RY0ARpe6/677-add-indexes-to-ethworker-db)

**Review by enjeyw — APPROVED** [review]
LGTM!

**Review by enjeyw — CHANGES_REQUESTED** [review]
Oh actually can u set one on the synchronised block as well (see below)
Screen Shot 2020-11-17 at 4 05 17 pm

**Comment by michielderoos** [comment]
> Oh actually can u set one on the synchronised block as well (see below)
> Screen Shot 2020-11-17 at 4 05 17 pm

@enjeyw Done!

**Review by enjeyw — APPROVED** [review]
LGTM! This also goes in the "Be very careful about merging this into production, as we need to make sure the migration on eth_worker db wont fail" column

**Pull request merged**
