### PR TITLE
CSV Export

### PR DESCRIPTION
**Pull request by michielderoos**
**Describe the Pull Request**

Adds option to export CSV files from to charts on the frontend  

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [x] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver

### CODE REVIEW

**Comment by michielderoos** [comment]
[Export metrics as CSV](https://trello.com/c/fT3NHpvs/772-export-metrics-as-csv)

**Review by tristanhcole — CHANGES_REQUESTED** [review]
Close to good to go!

Two small pieces of Feedback:

1. I think using an ant design icon, such as `<TableOutlined />` with a `Tooltip` wrapper, in the top left corner would work really cleanly. Especially as we could have another icon for PSD export. See rough mockup.
Screen Shot 2021-03-10 at 4 42 26 pm

2. There is a weird header? 
Screen Shot 2021-03-10 at 4 44 41 pm

**Comment by michielderoos** [comment]
> Close to good to go!
> 
> Two small pieces of Feedback:
> 
> 1. I think using an ant design icon, such as `<TableOutlined />` with a `Tooltip` wrapper, in the top left corner would work really cleanly. Especially as we could have another icon for PSD export. See rough mockup.
> 
> Screen Shot 2021-03-10 at 4 42 26 pm
> 
> 1. There is a weird header?
> 
> Screen Shot 2021-03-10 at 4 44 41 pm

Got the icon!  
The `None` was just what we call the single line with `ungrouped` charts. It is pretty obscure though, so I changed it to `Value` in that case!

**Review by tristanhcole — APPROVED** [review]
Great! I just added some spacing around `{cardTitle} {csvLink}`

**Pull request merged**
