### PR TITLE
Do things needed for static on S3

### PR DESCRIPTION
**Pull request by michielderoos**
**Describe the Pull Request**

Most of the work for this is in AWS, but we need a few things here:  
- Webpack doesn't need to make gzipped files anymore, cloudfront does that for us  
- We don't have to redirect anymore, cloudfront does that for us too  
- We have to upload the updated static assets to a dev bucket on deploy 
  
**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [x] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver
- [ ] Add release notes to [unreleased changelog](https://github.com/teamsempo/SempoBlockchain/blob/master/CHANGELOG.md#unreleased)

### CODE REVIEW

**Comment by michielderoos** [comment]
[Gzip in Webpack](https://trello.com/c/1wXpvPgm/963-gzip-in-webpack)

**Comment by michielderoos** [comment]
[Move static assets to S3](https://trello.com/c/xeMm5gJA/964-move-static-assets-to-s3)

**Comment by michielderoos** [comment]
[Take a look at smaller webpack](https://trello.com/c/07pZYDmP/961-take-a-look-at-smaller-webpack)

**Comment by michielderoos** [comment]
[Vulnerable TLS Protocol is in use](https://trello.com/c/tNyiYvIU/976-vulnerable-tls-protocol-is-in-use)

**Comment by michielderoos** [comment]
[Vulnerable TLS Protocol is in use](https://trello.com/c/tNyiYvIU/976-vulnerable-tls-protocol-is-in-use)

**Comment by michielderoos** [comment]
[Encryption - Weak Ciphers](https://trello.com/c/qQDk35FA/970-encryption-weak-ciphers)

**Review by tristanhcole — APPROVED** [review]
Need to add to deployment docs to update S3 static files.

LGTM! Nice work on this @michielderoos

**Comment by tristanhcole** [comment]
[Vulnerable TLS Protocol is in use](https://trello.com/c/bgtZfV9w/992-vulnerable-tls-protocol-is-in-use)

**Comment by tristanhcole** [comment]
[Encryption - Weak Ciphers](https://trello.com/c/oBOdrPBe/986-encryption-weak-ciphers)

**Pull request merged**
