### PR TITLE
Change to how long ago to real time

### PR DESCRIPTION
**Pull request by michielderoos**
**Describe the Pull Request**

Changes from "2 hours ago" to a real real timestamp.
image

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [x] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver

### CODE REVIEW

**Comment by michielderoos** [comment]
[An actual date/time might be better for “Created"](https://trello.com/c/ZcN0HzwI/755-an-actual-date-time-might-be-better-for-created)

**Review by tristanhcole — COMMENTED** [review]
I'm actually not sure about a Datetime for items created recently (i.e. live feed). Would be good to get @enjeyw's thoughts.

Screen Shot 2021-03-04 at 9 33 36 am

**Review by enjeyw — COMMENTED** [review]
@tristanhcole yeah i'm inclined to think that on the live feed it should remain the same (looks good to go in other locations though)

**Comment by michielderoos** [comment]
> @tristanhcole yeah i'm inclined to think that on the live feed it should remain the same (looks good to go in other locations though)

It's relative sometimes now!

**Review by tristanhcole — APPROVED** [review]
untested but changes lgtm!

**Pull request merged**
