### PR TITLE
Re-Enable Caching for Metrics

### PR DESCRIPTION
**Pull request by michielderoos**
**Describe the Pull Request**
  
Sets up caching for the current metrics incarnation. Group-by is now supported, and all our timeseries metrics are cached.   
Also adds a config for a cache timeout. When a metric isn't accessed for a week (or however long), the cache self-invalidated.  
This + #531 is a pretty big perf bump!

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes etc.
- [x] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver

### CODE REVIEW

**Comment by michielderoos** [comment]
[Re-enable caching for metrics](https://trello.com/c/aKF9F7rt/668-re-enable-caching-for-metrics)

**Review by tristanhcole — CHANGES_REQUESTED** [review]
I'm getting the following error:

```
INFO:werkzeug:127.0.0.1 - - [07/Jan/2021 17:30:44] "GET /api/v1/metrics/?metric_type=credit_transfer&disable_cache=true&group_by=ungrouped HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/sentry_sdk/integrations/flask.py", line 90, in sentry_patched_wsgi_app
    environ, start_response
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/sentry_sdk/integrations/wsgi.py", line 129, in __call__
    reraise(*_capture_exception(hub))
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 55, in reraise
    raise value
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/sentry_sdk/integrations/wsgi.py", line 125, in __call__
    _sentry_start_response, start_response, transaction
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/sentry_sdk/integrations/flask.py", line 89, in <lambda>
    return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/tristancole/VirtualEnvs/SempoBlockchain_env7/lib/python3.7/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/Users/tristancole/PycharmProjects/SempoBlockchain/app/server/utils/auth.py", line 44, in wrapper
    return f(*args, **kwargs)
  File "/Users/tristancole/PycharmProjects/SempoBlockchain/app/server/utils/auth.py", line 240, in wrapper
    return f(*args, **kwargs)
  File "/Users/tristancole/PycharmProjects/SempoBlockchain/app/server/api/metrics_api.py", line 58, in get
    if group_by not in groups.GROUP_TYPES.keys():
  File "/Users/tristancole/PycharmProjects/SempoBlockchain/app/server/utils/metrics/group.py", line 97, in GROUP_TYPES
    custom_attribute_groups = get_custom_attribute_groups()
  File "/Users/tristancole/PycharmProjects/SempoBlockchain/app/server/utils/metrics/group.py", line 82, in get_custom_attribute_groups
    groups[ao] = Group(ao.capitalize(), CustomAttributeUserStorage, CustomAttributeUserStorage.value, ao)
AttributeError: 'NoneType' object has no attribute 'capitalize'
INFO:werkzeug:127.0.0.1 - - [07/Jan/2021 17:30:44] "GET /static/media/favicons/favicon.ico HTTP/1.1" 200 -

```

Screen Shot 2021-01-07 at 5 16 16 pm

**Review by michielderoos — COMMENTED** [review]
@tristanhcole It is working for me, (after merging master in). There were some changes to how custom attributes worked in that master-merge, so I suspect that made it work. Care to have another look after updating your branch?

**Comment by tristanhcole** [comment]
> @tristanhcole It is working for me, (after merging master in). There were some changes to how custom attributes worked in that master-merge, so I suspect that made it work. Care to have another look after updating your branch?

Ok, that might be it, will look now!

**Review by tristanhcole — APPROVED** [review]
Tested and works for me!

**Pull request merged**
