### PR TITLE
New Transfer Account List Frontend

### PR DESCRIPTION
**Pull request by enjeyw**
**Describe the Pull Request**

Refactoring of the front-end transfer list into its own PR.

Supersedes https://github.com/teamsempo/SempoBlockchain/pull/610

**Todo**

- [ ] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [ ] Request review from relevant @person or team
- [ ] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [ ] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver

### CODE REVIEW

**Comment by tristanhcole** [comment]
Also closes #205

**Review by michielderoos — CHANGES_REQUESTED** [review]
This looks good, love the UI! It should not be merged in though, since disbursement, approval, and unapproval don't work! I also noticed that it's not using the pagination at all, is that in an upstream PR?

**Comment by enjeyw** [comment]
> This looks good, love the UI! It should not be merged in though, since disbursement, approval, and unapproval don't work! I also noticed that it's not using the pagination at all, is that in an upstream PR?

Yeah agree should only be merged once the bulk disbursement goes in. When u refer to pagination, do u mean at a UI or API level? Antd automatically does pagination on the table.

**Comment by michielderoos** [comment]
> > This looks good, love the UI! It should not be merged in though, since disbursement, approval, and unapproval don't work! I also noticed that it's not using the pagination at all, is that in an upstream PR?
> 
> Yeah agree should only be merged once the bulk disbursement goes in. When u refer to pagination, do u mean at a UI or API level? Antd automatically does pagination on the table.

@enjeyw I mean api level, since now it's still loading every single account

**Comment by tristanhcole** [comment]
Note: there might be on or two fixes in here that weren't included in #615

**Pull request closed without merging**
