### PR TITLE
Consistent naming of user types

### PR DESCRIPTION
**Pull request by enjeyw**
**Describe the Pull Request**

Ensuring that user types are consistently named:
- All users who are subjects of a program are "Participants"
- All users who administer a program are "Admins"

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes etc.
- [ ] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver

### CODE REVIEW

**Comment by enjeyw** [comment]
https://trello.com/c/bGS17Tyz

**Comment by tristanhcole** [comment]
> All users who are subjects of a program are "Participants"

I personally like "beneficiary" more, but understand that NGOs seems to be so polarized by that word

**Review by tristanhcole — CHANGES_REQUESTED** [review]
Looks good to me but a few thoughts...

> All users who are subjects of a program are "Participants"
If this is the case, then the config `BENEFICIARY_TERM_PLURAL` and `BENEFICIARY_TERM` should be deprecated in this PR also as the term "Beneficiary" (or whatever the config is set to) is also seen through out the software

**Comment by tristanhcole** [comment]
[Consistent and Explicit Labelling of User Types Across Entire Platform](https://trello.com/c/bGS17Tyz/511-consistent-and-explicit-labelling-of-user-types-across-entire-platform)

**Comment by enjeyw** [comment]
> > All users who are subjects of a program are "Participants"
> 
> I personally like "beneficiary" more, but understand that NGOs seems to be so polarized by that word

To be clear, "participants" refers to both "Beneficiaries" and "Vendors" (Etc etc etc)  - it's all users who aren't admins.

**Comment by enjeyw** [comment]
> Looks good to me but a few thoughts...
> 
> > All users who are subjects of a program are "Participants"
> > If this is the case, then the config `BENEFICIARY_TERM_PLURAL` and `BENEFICIARY_TERM` should be deprecated in this PR also as the term "Beneficiary" (or whatever the config is set to) is also seen through out the software

Given my other comment, I don't _think_ this is the same PR (as Beneificiary is still a used phrase). That said I quite like the idea of biting the bullet and just calling beneficiaries beneficiaries.

**Comment by enjeyw** [comment]
@tristanhcole checking in that i don't think this is actually a deprecation (see above comments)?

**Comment by tristanhcole** [comment]
> Given my other comment, I don't _think_ this is the same PR (as Beneificiary is still a used phrase). That said I quite like the idea of biting the bullet and just calling beneficiaries beneficiaries.

I think we should

**Review by tristanhcole — APPROVED** [review]
LGTM

**Pull request merged**
