### PR TITLE
Calculate metrics percentages on the backend

### PR DESCRIPTION
**Pull request by michielderoos**
**Describe the Pull Request**

Percentages were being calculated incorrectly, and on the front end. Now percentages are calculated correctly, and on the backend!

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes etc.
- [x] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver

### CODE REVIEW

**Comment by michielderoos** [comment]
[Fix Plus/Minus Custom Tabs](https://trello.com/c/qrZxmcq1/577-fix-plus-minus-custom-tabs)

**Review by tristanhcole — CHANGES_REQUESTED** [review]
Light QA seems to returns `-100%` always?

Also tried running different queries and date ranges

Screen Shot 2020-10-02 at 8 15 39 am

**Review by tristanhcole — CHANGES_REQUESTED** [review]
@michielderoos can we filter out `percent_change` from `const aggregateKeys` in L23 of `GroupByChart.jsx`. Otherwise it shows up in chart (see screenshot) and doesn't really make sense to me.

Screen Shot 2020-10-06 at 2 26 17 pm

**Comment by michielderoos** [comment]
> @michielderoos can we filter out `percent_change` from `const aggregateKeys` in L23 of `GroupByChart.jsx`. Otherwise it shows up in chart (see screenshot) and doesn't really make sense to me.
> 
> Screen Shot 2020-10-06 at 2 26 17 pm

@tristanhcole Good point, fixed!

**Review by tristanhcole — APPROVED** [review]
Tested! Good to go! 🎸

**Pull request merged**
