### PR TITLE
Enable Pusher Batching

### PR DESCRIPTION
**Pull request by michielderoos**
Send pusher requests in batches when doing bulk operations.  
This is ready for review, but should **not** be pushed until #240 is merged

### CODE REVIEW

**Comment by michielderoos** [comment]
[Make pusher push updates in batch when relevant](https://trello.com/c/VstIniRc/455-make-pusher-push-updates-in-batch-when-relevant)

**Comment by michielderoos** [comment]
@enjeyw   
Makes sense. I have a 2nd PR up which defers transactions _and_ does the bulk pushing afterwards. I based it on this one to make the diff readable, but on approval we can merge this, then immediately merge that one afterwards (I think it makes sense to have these PRs both be separate/semi-atomic)  
https://github.com/teamsempo/SempoBlockchain/pull/248

**Comment by tristanhcole** [comment]
> @enjeyw
> Makes sense. I have a 2nd PR up which defers transactions _and_ does the bulk pushing afterwards. I based it on this one to make the diff readable, but on approval we can merge this, then immediately merge that one afterwards (I think it makes sense to have these PRs both be separate/semi-atomic)
> #248

Nice, that makes it super clean and I'm sure some big perf improvements

**Comment by tristanhcole** [comment]
Could you please resolve these conflicts @michielderoos?

**Pull request merged**
