### PR TITLE
Add notes to disbursement

### PR DESCRIPTION
**Pull request by michielderoos**
**Describe the Pull Request**

Add notes to disbursement  

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [x] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver
- [ ] Add release notes to [unreleased changelog](https://github.com/teamsempo/SempoBlockchain/blob/master/CHANGELOG.md#unreleased)

### CODE REVIEW

**Comment by michielderoos** [comment]
[[Feedback] (2 hour) Bulk disbursement notes](https://trello.com/c/DBPLiJaq/818-feedback-2-hour-bulk-disbursement-notes)

**Comment by michielderoos** [comment]
[Disbursements page loses all data on refresh](https://trello.com/c/F7csVOio/805-disbursements-page-loses-all-data-on-refresh)

**Review by tristanhcole — CHANGES_REQUESTED** [review]
A few small comments.

1) Notes still showing as editable, even though they're not.
Screen Shot 2021-04-27 at 10 34 22 am

2) Notes don'ts seem to be editable on partial approvals
Screen Shot 2021-04-27 at 10 33 54 am

Alternatively - could use an editable paragraph component that saves once the user has finished typing https://ant.design/components/typography/#components-typography-demo-interactive. This could be good as it would mean the notes section can be updated even once the transfer is approved or rejected.

**Review by tristanhcole — APPROVED** [review]
👍

**Pull request merged**
