### PR TITLE
Add resolution messages to credit transfer page

### PR DESCRIPTION
**Pull request by michielderoos**
**Describe the Pull Request**

Adds resolution messages to credit transfer page  

**Todo**

- [x] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [x] Request review from relevant @person or team
- [x] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [x] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver
- [ ] Add release notes to [unreleased changelog](https://github.com/teamsempo/SempoBlockchain/blob/master/CHANGELOG.md#unreleased)

### CODE REVIEW

**Comment by michielderoos** [comment]
[Add transaction errors to txn info page](https://trello.com/c/uNoYxB65/1036-add-transaction-errors-to-txn-info-page)

**Review by tristanhcole — COMMENTED** [review]
I feel like we could format the message a little better. Could make sense to remove the resolution DateTime, as it's effectively already there as "Date Resolved"

You could split on "::" and just show the second half of the message?

What do you think?

Screen Shot 2022-06-09 at 11 39 00 am

**Comment by tristanhcole** [comment]
Also, could be good to remove the brackets?

**Comment by michielderoos** [comment]
> Also, could be good to remove the brackets?

Yeah, the error message is pretty verbose. Just simplified it on the BE, no need to have all that data there!

**Review by tristanhcole — APPROVED** [review]
Simple is better

**Pull request merged**
